# Regresión lineal en python
## EL paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [5]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X, Y)

In [6]:
selector.support_

array([ True,  True, False], dtype=bool)

In [7]:
selector.ranking_

array([1, 1, 2])

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
x_pred = X[["TV", "Radio"]]

In [10]:
lm = LinearRegression()
lm.fit(x_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
lm.intercept_

2.9210999124051362

In [12]:
lm.coef_

array([ 0.04575482,  0.18799423])

In [13]:
lm.score(x_pred, Y)

0.89719426108289557